---
- name: Provision Personal Computer
  hosts: "localhost,"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - common
  vars:
    user_name: julian
    git_email: "julianlawrence@gmail.com"
    git_name: "Julian Lawrence"
    go_url: "https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz"
    go_checksum: "fa1b0e45d3b647c252f51f5e1204aba049cde4af177ef9f2181f43004f901035"
