- name: Apt Update
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Apts
  apt: pkg="{{ item }}" state="present"
  with_items:
    - software-properties-common
    - curl
    - openssh-server
    - fail2ban
    - build-essential
    - python-dev
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - vim
    - git
    - docker.io
    - direnv
    - tilix
    - cmake
    - fonts-powerline

- name: apt cache cleanup
  apt:
    autoclean: yes
    autoremove: yes
