---
- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y

- name: Apt Update
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Programs
  apt: pkg="{{ item }}" state="present"
  with_items:
    - software-properties-common
    - openssh-server
    - build-essential
    - fail2ban
    - python3-dev
    - python3-pip
    - python-dev
    - python-pip
    - curl
    - traceroute
    - vim
    - git
    - docker.io
    - openvpn

- name: Install Python deps
  pip: name={{ item }}
  with_items:
    - awscli
    - autoenv  

# SSH Config
- name: Install User SSH keys
  authorized_key:
    user: "{{user_name}}"
    state: present
    key: "{{item}}"
  with_file:
    - keys/id_rsa.pub
  
- name: Prepare {{ user_name }} .ssh file
  file:
    path: /home/{{ user_name }}/.ssh
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0700

- name: Ensure private key exists
  copy:
    dest: /home/{{ user_name }}/.ssh/id_rsa
    src: keys/id_rsa
    mode: 0400
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

- name: Ensure public key exists
  copy:
    dest: /home/{{ user_name }}/.ssh/id_rsa.pub
    src: keys/id_rsa.pub
    mode: 0400
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

- name: Ensure config exists
  copy:
    dest: /home/{{ user_name }}/.ssh/config
    src: keys/config
    mode: 0600
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

- name: Copy sshd config
  copy:
    dest: /etc/ssh/sshd_config
    src: keys/sshd_config
    owner: 'root'
    group: 'root'
    mode: 0644

- ufw:
    rule: allow
    name: OpenSSH
    
# Git Config
- name: Git Name
  git_config:
    name: user.name
    scope: global
    value: '{{ git_name }}'

- name: Git Email
  git_config:
    name: user.email
    scope: global
    value: '{{ git_email }}'

# GO
- name: Download GO
  get_url:
    url: "{{ go_url }}"
    dest: /tmp/go.tar.gz
    checksum: sha256:"{{ go_checksum }}"

- name: Unarchive Go
  unarchive: 
    creates: /usr/local/go
    src: /tmp/go.tar.gz
    dest: /usr/local

- name: Update {{ user_name }} profile
  lineinfile:
    dest: '/home/{{ user_name }}/.profile'
    line: 'export PATH=$PATH:/usr/local/go/bin'

- name: Update {{ user_name }} bashrc
  blockinfile:
    dest: '/home/{{ user_name }}/.bashrc'
    block: |
      export GOPATH=$HOME/go
      export PATH=$PATH:$GOPATH/bin
      export PATH=$PATH:/home/julian/Applications/protoc-3.1.0-linux-x86_64/bin
      source /usr/local/bin/activate.sh
      alias got='go test -v --cover ./...'
      alias gfs='git flow feature start'
      alias gff='git flow feature finish'
      alias grs='git flow release start'
      alias grf='git flow release finish'

# Docker
- name: Add User to Docker Group
  command: sudo usermod -aG docker {{ user_name }}
