---
- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y

- name: Apt Update
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Programs
  apt: pkg="{{ item }}" state="present"
  with_items:
    - build-essential
    - fail2ban
    - python3-dev
    - python3-pip
    - python-dev
    - python-pip
    - curl
    - traceroute
    - vim
    - git
    - docker.io
    - openvpn

# Git Config
- name: Git Name
  git_config:
    name: user.name
    scope: global
    value: '{{ git_name }}'

- name: Git Email
  git_config:
    name: user.email
    scope: global
    value: '{{ git_email }}'

# GO
- name: Download GO
  get_url:
    url: "{{ go_url }}"
    dest: /tmp/go.tar.gz
    checksum: sha256:"{{ go_checksum }}"

- name: Unarchive Go
  unarchive: 
    creates: /usr/local/go
    src: /tmp/go.tar.gz
    dest: /usr/local

- name: Update {{ user_name }} profile
  lineinfile:
    dest: '/home/{{ user_name }}/.profile'
    line: 'export PATH=$PATH:/usr/local/go/bin'

- name: Update {{ user_name }} bashrc
  blockinfile:
    dest: '/home/{{ user_name }}/.bashrc'
    block: |
      export GOPATH=$HOME/go
      export PATH=$PATH:$GOPATH/bin
      alias got='go test -v --cover ./...'
      alias gfs='git flow feature start'
      alias gff='git flow feature finish'
      alias grs='git flow release start'
      alias grf='git flow release finish'

# Docker
- name: Add User to Docker Group
  command: sudo usermod -aG docker {{ user_name }}
