- name: Prepare {{ user_name }} .ssh file
  file:
    path: /home/{{ user_name }}/.ssh
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0700

- name: Ensure private key exists
  copy:
    dest: /home/{{ user_name }}/.ssh/id_rsa
    src: .ssh/id_rsa
    mode: 0400
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

- name: Ensure public key exists
  copy:
    dest: /home/{{ user_name }}/.ssh/id_rsa.pub
    src: .ssh/id_rsa.pub
    mode: 0400
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

- name: Ensure config exists
  copy:
    dest: /home/{{ user_name }}/.ssh/config
    src: .ssh/config
    mode: 0600
    owner: '{{ user_name }}'
    group: '{{ user_name }}'